# Generated by Django 3.1.3 on 2020-12-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=225)),
                ('description', models.TextField(null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Todo'), (2, 'Doing'), (3, 'Done'), (4, 'Cancelled')], default=1)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Unset'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_todo', models.DateTimeField(null=True)),
                ('date_done', models.DateTimeField(null=True)),
                ('copy_of', models.PositiveSmallIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
